### ISSUE TITLE
openvpn.sh does not generate server.crt/server.key

### ISSUE THREAD

**Issue by devendralaulkar** [redgeoff/openvpn-server-vagrant#1]
Steps to reproduce:
wget https://github.com/redgeoff/openvpn-server-vagrant/archive/master.zip
unzip master.zip 
cd openvpn-server-vagrant-master/
./openvpn.sh 

build-key-server does not execute, which in turn does not generate server.crt & server.key

./openvpn.sh: line 38: ./build-key-server.sh: No such file or directory

[log.txt](https://github.com/redgeoff/openvpn-server-vagrant/files/1196140/log.txt)
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.3 LTS"
Linux ip-10-0-3-233 4.4.0-1022-aws #31-Ubuntu SMP Tue Jun 27 11:27:55 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**Comment by devendralaulkar** [comment]
This issue can be solved by manually generating the server certificate
cd ~/openvpn-ca/
source vars
./build-key-server server
cd ~/openvpn-ca/keys
cp server.crt server.key /etc/openvpn/
systemctl status openvpn@server.service

**Comment by redgeoff** [comment]
Hey @devendralaulkar, there are two supported installation paths:

The first is described at [Set up](https://github.com/redgeoff/openvpn-server-vagrant#set-up).

The second is described in the _Install and Configure the OpenVPN Server_ section at https://medium.com/@redgeoff/using-a-vpn-server-to-connect-to-your-aws-vpc-for-just-the-cost-of-an-ec2-nano-instance-3c81269c71c2.

I'm pretty sure that both of these paths are working, but please let me know if you find otherwise.

**Comment by devendralaulkar** [comment]
I am following your Medium post.
The issue probably arises if you execute openvpn.sh from inside the openvpn-server-vagrant directory (vs calling it via the full expanded path)
I was able to get it work after using the full expanded path.
